import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { fileURLToPath } from "url";
import { dirname, resolve, join } from "path";
import { createRequire } from "module";

const __dirname = dirname(fileURLToPath(import.meta.url));
const nodeModulesPath = resolve(__dirname, "node_modules");

// Custom plugin to resolve packages from local node_modules,
// bypassing any Yarn PnP hooks that may be active in the parent environment.
const localResolvePlugin = {
  name: "local-resolve",
  setup(build) {
    // Intercept bare module specifiers (not relative/absolute paths)
    build.onResolve({ filter: /^[^./]/ }, (args) => {
      // Skip packages already marked external
      if (build.initialOptions.external?.includes(args.path)) return null;
      // Skip built-in Node modules
      if (builtins.includes(args.path)) return null;

      // Try to resolve from local node_modules
      try {
        const localRequire = createRequire(join(nodeModulesPath, "dummy.js"));
        const resolved = localRequire.resolve(args.path);
        return { path: resolved };
      } catch {
        return null; // Let esbuild handle it normally
      }
    });
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  nodePaths: [nodeModulesPath],
  plugins: [localResolvePlugin],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
